medicine/medicine/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from users.forms import UserCreationForm
from django.views.generic import CreateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include('pages.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('auth/registration/', CreateView.as_view(
        template_name='registration/registration_form.html',
        form_class=UserCreationForm,
        success_url=reverse_lazy('profile:profile_create')
    ), name='registration'),
    path('news/', include('news.urls')),
    path('profile/', include('user_settings.urls')),
    path('patients/', include('patients.urls')),
    path('appointments/', include('appointment.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

medicine/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('',
         views.NewsArticleListView.as_view(),
         name='news_article_list'
         ),
    path(
        'create/',
        views.CreateNewsArticleView.as_view(),
        name='create_news_article'
    ),
    path(
        '<int:pk>/',
        views.NewsArticleDetailView.as_view(),
        name='news_article_detail'
    ),
    path("<int:pk>/update/",
         views.UpdateNewsArticleView.as_view(),
         name="update_news_article"
         #  TODO: изменить название! news_update_article
         ),
    path(
        '<int:pk>/delete/',
        views.NewsArticleDeleteView.as_view(),
        name='news_article_delete'
    ),
]

medicine/user_settings/urls.py
from django.urls import path
from . import views

app_name = 'profile'

urlpatterns = [
    path(
        # "<int:pk>/",
        '',
        views.DetailViewProfile.as_view(),
        name="profile_view"
    ),
    path(
        "create/",
        views.CreateViewProfile.as_view(),
        name="profile_create"
    ),
    path(
        "role/",
        views.ProfileChooseRoleView.as_view(),
        name="profile_choose_role"
    ),
    path(
        # '<int:pk>/edit/',
        'edit/',
        views.UpdateViewProfile.as_view(),
        name='profile_edit'
    ),

]

medicine/doctors/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Specialization(models.Model):
    name = models.CharField(
        max_length=100,
        verbose_name="Название специализации"
    )
    description = models.TextField(
        blank=True,
        null=True,
        verbose_name="Описание специализации"
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Специализация"
        verbose_name_plural = "Специализации"
        ordering = ['name']

    def __str__(self):
        return self.name


class Doctor(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='doctor'
    )

    specialization = models.ForeignKey(
        Specialization,
        on_delete=models.SET_NULL,  # если специализация удалена, оставляем NULL
        null=True,
        blank=False,
        related_name='doctors',
        verbose_name="Специализация"
    )

    category = models.CharField(
        max_length=50,
        verbose_name="Квалификационная категория",
        blank=True,
        null=True,
        choices=[
            ("no", "Без категории"),
            ("2", "Вторая категория"),
            ("1", "Первая категория"),
            ("top", "Высшая категория"),
        ]
    )

    medical_license_number = models.CharField(
        max_length=30,
        verbose_name="Номер медицинской лицензии",
        blank=True,
        null=True
    )

    medical_organization = models.CharField(
        max_length=255,
        verbose_name="Медицинская организация",
        blank=True,
        null=True
    )

    preview_info = models.TextField(
        verbose_name="Информация превью",
        blank=True,
        null=True
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Доктор"
        verbose_name_plural = "Доктора"

    def __str__(self):
        return f"Доктор {self.get_full_name()} ({self.specialization})"

    def get_full_name(self):
        return self.user.settings.get_full_name()

medicine/templates/includes/header.html
<!-- templates/includes/header.html -->
<header>
  <nav class="navbar shadow-sm">
    <div class="container">
      {% with request.resolver_match.view_name as view_name %}
        <ul class="nav nav-pills">
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'pages:homepage' %} active {% endif %}"
              href="{% url 'pages:homepage' %}">
              Главная
            </a>
          </li>
          <li class ="nav-item">
            <a class="nav-link {% if view_name == 'news:news_article_list' %} active {% endif %}" href="{% url 'news:news_article_list' %}" >Новости</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'appointment:specialization_list' %} active {% endif %}" href="{% url 'appointment:specialization_list' %}">
              Запись на приём
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'appointment:my_appointments' %} active {% endif %}" href="{% url 'appointment:my_appointments' %}">
              Мои записи
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'pages:contacts' %} active {% endif %}" href="{% url 'pages:contacts' %}">
              Контакты
            </a>
          </li>
        </ul>

          <ul class="nav nav-pills ms-auto">
          {% if user.is_authenticated %}
            <span class="navbar-text">Пользователь: <b>{{ user.email }}</b></span>

            {% if view_name != 'profile:profile_create' %}
            <li class="nav-item">
                <a class="nav-link{% if view_name == 'profile' %} active {% endif %}" href="{% url 'profile:profile_view' %}">Профиль</a>
            </li>
            {% endif %}

            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link{% if view_name == 'login' %} active {% endif %}" href="{% url 'login' %}">Войти</a>
            </li>
            <li class="nav-item">
              <a class="nav-link{% if view_name == 'registration' %} active {% endif %}" href="{% url 'registration' %}">Регистрация</a>
            </li>
          {% endif %}
        </ul>
      {% endwith %}
    </div>
  </nav>
</header>

medicine/templates/includes/news_list_short.html
<div class="row">
    {% for news in news_list %}
      <div class="col-12 mb-4">
        <div class="card h-100 border-0 shadow-sm">
          {% if news.image %}
            <img src="{{ news.image.url }}" class="card-img-top" style="width:100%; height:300px; object-fit: cover;" alt="{{ news.title }}">
          {% endif %}
          <div class="card-body d-flex flex-column">
            <h5 class="card-title">{{ news.title }}</h5>
            <p class="card-text text-truncate" style="display: -webkit-box; -webkit-line-clamp: 5; -webkit-box-orient: vertical; overflow: hidden;">
              {{ news.content }}
            </p>
            <a href="{{ news.get_absolute_url }}" class="btn btn-primary mt-auto align-self-start">Читать далее</a>
          </div>
          <div class="card-footer text-muted bg-white border-0">
            <small>{{ news.published_date|date:"d.m.Y" }}</small>
          </div>
        </div>
      </div>
    {% empty %}
      <div class="col-12">
        <p class="text-muted">Пока новостей нет.</p>
      </div>
    {% endfor %}
</div>