medicine/medicine/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from users.forms import UserCreationForm
from django.views.generic import CreateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include('pages.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('auth/registration/', CreateView.as_view(
        template_name='registration/registration_form.html',
        form_class=UserCreationForm,
        success_url=reverse_lazy('profile:profile_create')
    ), name='registration'),
    path('news/', include('news.urls')),
    path('profile/', include('user_settings.urls')),
    path('patients/', include('patients.urls')),
    path('appointments/', include('appointment.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

medicine/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('',
         views.NewsArticleListView.as_view(),
         name='news_article_list'
         ),
    path(
        'create/',
        views.CreateNewsArticleView.as_view(),
        name='create_news_article'
    ),
    path(
        '<int:pk>/',
        views.NewsArticleDetailView.as_view(),
        name='news_article_detail'
    ),
    path("<int:pk>/update/",
         views.UpdateNewsArticleView.as_view(),
         name="update_news_article"
         #  TODO: изменить название! news_update_article
         ),
    path(
        '<int:pk>/delete/',
        views.NewsArticleDeleteView.as_view(),
        name='news_article_delete'
    ),
]

medicine/patients/urls.py
from django.urls import path
from . import views

app_name = 'patients'

urlpatterns = [
    path(
        'create/',
        views.PatientCreateView.as_view(),
        name='patient_create'
    ),
]

medicine/user_settings/urls.py
from django.urls import path
from . import views

app_name = 'profile'

urlpatterns = [
    path(
        # "<int:pk>/",
        '',
        views.DetailViewProfile.as_view(),
        name="profile_view"
    ),
    path(
        "create/",
        views.CreateViewProfile.as_view(),
        name="profile_create"
    ),
    path(
        "role/",
        views.ProfileChooseRoleView.as_view(),
        name="profile_choose_role"
    ),
    path(
        # '<int:pk>/edit/',
        'edit/',
        views.UpdateViewProfile.as_view(),
        name='profile_edit'
    ),

]

medicine/user_settings/models.py
from django.db import models
from django.contrib.auth import get_user_model
from .validators import real_age, check_snils, check_phone, check_string_only

User = get_user_model()


class UserSettings(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='settings'
    )

    first_name = models.CharField(
        'Имя',
        max_length=40,
        blank=False,
        validators=(check_string_only,)
    )
    last_name = models.CharField(
        'Фамилия',
        max_length=40,
        blank=False,
        validators=(check_string_only,)
    )
    middle_name = models.CharField(
        'Отчество',
        blank=True,
        max_length=40,
        help_text='Необязательное поле',
        validators=(check_string_only,)
    )

    gender = models.CharField(
        'Пол',
        max_length=1,
        choices=(
            ('M', 'Мужской'),
            ('F', 'Женский'),
        ),
        blank=True
    )

    snils = models.CharField(
        max_length=14,
        unique=True,
        verbose_name="СНИЛС",
        validators=(check_snils,)
    )

    phone = models.CharField(
        'Телефон',
        max_length=20,
        unique=True,
        blank=True,
        validators=(check_phone,)
    )

    date_of_birth = models.DateField(
        'Дата рождения',
        validators=(real_age,),
        null=True,
        blank=True,
    )

    def __str__(self):
        return f'Настройки пользователя {self.user.email}'

    def get_full_name(self):
        return f"{self.last_name} {self.first_name} {self.middle_name}"

medicine/templates/profile/profile_choose_role.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-md-6">

            <h2 class="text-center mb-4">Кого зарегистрировать?</h2>

            <div class="d-grid gap-3">
                <a href="{% url 'patients:patient_create' %}" class="btn btn-secondary btn-lg">
                    Регистрация пациента
                </a>

                {% comment %} <a href="{% url 'doctor:register_doctor' %}" class="btn btn-secondary btn-lg"> {% endcomment %}
                <a href="#" class="btn btn-primary btn-lg">
                    Регистрация врача
                </a>
            </div>

        </div>
    </div>
</div>
{% endblock %}

medicine/templates/profile/profile_create_form.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-md-8 col-lg-6">

            <h2 class="mb-4 text-center">Настройка профиля</h2>

            <form method="post" class="card p-4 shadow-sm rounded-4">
                {% csrf_token %}

                <div class="row">
                    {{ form.email.as_hidden }}

                    <div class="col-md-6 mb-3">
                        {% bootstrap_field form.last_name %}
                    </div>

                    <div class="col-md-6 mb-3">
                        {% bootstrap_field form.first_name %}
                    </div>

                    <div class="col-md-12 mb-3">
                        {% bootstrap_field form.middle_name %}
                    </div>

                    <div class="col-md-6 mb-3">
                        {% bootstrap_field form.gender %}
                    </div>

                    <div class="col-md-6 mb-3">
                        {% bootstrap_field form.phone %}
                    </div>

                    <div class="col-md-12 mb-3">
                        {% bootstrap_field form.date_of_birth %}
                    </div>

                    <div class="col-md-12 mb-3">
                        {% bootstrap_field form.snils %}
                    </div>
                </div>

                <div class="mb-3 form-check">
                    <input type="checkbox" class="form-check-input" id="consent" name="consent" required>
                    <label class="form-check-label" for="consent">
                        Я согласен на обработку персональных данных
                    </label>
                </div>

                <button type="submit" class="btn btn-primary w-100 mt-3">
                    Далее
                </button>
            </form>

        </div>
    </div>
</div>
{% endblock %}

medicine/templates/profile/profile_detail.html
{% extends "base.html" %}
{% block content %}

<h1 class="text-center mb-4">Профиль</h1>

<div class="container d-flex justify-content-center">
    <div class="card p-4 shadow-sm" style="max-width: 700px; width: 100%; border-radius: 15px;">

        <div class="mb-3">
            <label class="form-label">Адрес электронной почты</label>
            <input type="text" class="form-control" value="{{ user.email }}" disabled>
        </div>

        <div class="row mb-3">
            <div class="col">
                <label class="form-label">Фамилия</label>
                <input type="text" class="form-control" value="{{ data.last_name }}" disabled>
            </div>
            <div class="col">
                <label class="form-label">Имя</label>
                <input type="text" class="form-control" value="{{ data.first_name }}" disabled>
            </div>
        </div>

        <div class="mb-3">
            <label class="form-label">Отчество</label>
            <input type="text" class="form-control" value="{{ data.middle_name }}" disabled>
        </div>

        <div class="row mb-3">
            <div class="col">
                <label class="form-label">Пол</label>
                <input type="text" class="form-control" value="{{ data.get_gender_display }}" disabled>
            </div>
            <div class="col">
                <label class="form-label">Телефон</label>
                <input type="text" class="form-control" value="{{ data.phone }}" disabled>
            </div>
        </div>

        <div class="mb-4">
            <label class="form-label">Дата рождения</label>
            <input type="text" class="form-control" value="{{ data.date_of_birth|date:"d.m.Y" }}" disabled>
        </div>

        <div class="mb-3">
            <label class="form-label">СНИЛС</label>
            <input type="text" class="form-control" value="{{ data.snils }}" disabled>
        </div>

        <div class="d-flex justify-content-between mt-4">
            <a href="{% url 'profile:profile_edit' %}" class="btn btn-primary px-4">Редактировать</a>
            <a href="{% url 'password_change' %}" class="btn btn-outline-secondary px-4">Сменить пароль</a>
        </div>

    </div>
</div>

{% endblock %}

medicine/templates/profile/profile_edit_form.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
<h1 class="mb-4 text-center">Редактирование профиля</h2>
<div class="container d-flex justify-content-center">
    <div class="card p-4 shadow-sm" style="max-width: 700px; width: 100%; border-radius: 15px;">
            <form method="post">
                {% csrf_token %}

                <div class="mb-3">
                    {% bootstrap_field form.email %}
                </div>
                
                <div class="row mb-3">
                    <div class="col">
                        {% bootstrap_field form.last_name %}
                    </div>
                    <div class="col">
                        {% bootstrap_field form.first_name %}
                    </div>
                </div>

                <div class="mb-3">
                    {% bootstrap_field form.middle_name %}
                </div>
                
                <div class="row mb-3">
                    <div class="col">
                        {% bootstrap_field form.gender %}
                    </div>
                    <div class="col">
                        {% bootstrap_field form.phone %}
                    </div>
                </div>

                <div class="m4">
                    {% bootstrap_field form.date_of_birth %}
                </div>

                <div class="mb-3">
                    {% bootstrap_field form.snils %}
                </div>

                <button type="submit" class="btn btn-primary w-100 mt-3">
                    Сохранить
                </button>
            </form>
    </div>
</div>
{% endblock %}

medicine/templates/profile/profile_form.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-md-8 col-lg-6">

            <h2 class="mb-4 text-center">Редактирование профиля</h2>

            <form method="post" class="card p-4 shadow-sm rounded-4">
                {% csrf_token %}

                <div class="row">
                    <div class="col-md-6 mb-3">
                        {% bootstrap_field form.last_name %}
                    </div>

                    <div class="col-md-6 mb-3">
                        {% bootstrap_field form.first_name %}
                    </div>

                    <div class="col-md-12 mb-3">
                        {% bootstrap_field form.middle_name %}
                    </div>

                    <div class="col-md-6 mb-3">
                        {% bootstrap_field form.gender %}
                    </div>

                    <div class="col-md-6 mb-3">
                        {% bootstrap_field form.phone %}
                    </div>

                    <div class="col-md-12 mb-3">
                        {% bootstrap_field form.date_of_birth %}
                    </div>
                </div>

                <button type="submit" class="btn btn-primary w-100 mt-3">
                    Сохранить
                </button>
            </form>

        </div>
    </div>
</div>
{% endblock %}